In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

How many negative numbers are there?

In [4]:
negative_numbers = a < 0
negative_numbers
len(a[negative_numbers])

4

How many positive numbers are there?

In [5]:
positive_numbers = a > 0
positive_numbers
len(a[positive_numbers])

5

How many even positive numbers are there?



In [6]:
even_numbers = a % 2 == 0
len(a[even_numbers & positive_numbers])

3

If you were to add 3 to each data point, how many positive numbers would there be?



In [10]:
array_plus_three = a + 3
len(array_plus_three[positive_numbers])

5

If you squared each number, what would the new mean and standard deviation be?



In [14]:
num_sqrd = a ** 2
np.std(num_sqrd)

144.0243035046516

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [19]:
np.mean(a)
centered_array = a - np.mean(a)
centered_array


array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [20]:
np.mean(centered_array)

0.0

Calculate the z-score for each data point. Recall that the z-score is given by:

z = (x - mu)/sigma


In [23]:
z_score = (a - np.mean(a)) / np.std(a)
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [49]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array(a)

# Use python's built in functionality/operators to determine the following:

# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [50]:
sum_of_a = sum(a)
sum_of_a

55

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list



In [51]:
min_of_a = min(a)
min_of_a

1

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [52]:
max_of_a = max(a)
max_of_a

10

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [53]:
mean_of_a = np.mean(a)
mean_of_a

5.5

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [54]:
product_of_a = np.math.factorial(10)
product_of_a

3628800

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]



In [55]:
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [60]:
odds_in_a = a[a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [61]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.


In [80]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [81]:
b = np.array(b)

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)


In [82]:
np.sum(b)

33


# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [85]:
np.min(b)

3

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [91]:
np.max(b)

8

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [92]:
np.mean(b)

5.5

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [99]:
np.prod(b)

20160

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [100]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [115]:
np.reshape(np.square(b),(1,6))

array([[ 9, 16, 25, 36, 49, 64]])

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [112]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [113]:
b[b % 2 != 0]

array([3, 5, 7])

# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [116]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [117]:
b[b % 2 == 0]

array([4, 6, 8])

# Exercise 9 - print out the shape of the array b.

In [118]:
np.shape(b)

(2, 3)

# Exercise 10 - transpose the array b.

In [119]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [120]:
np.reshape(b,(1,6))

array([[3, 4, 5, 6, 7, 8]])

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [121]:
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [122]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c = np.array(c)

# Exercise 1 - Find the min, max, sum, and product of c.



In [123]:
np.min(c)

1

In [124]:
 np.max(c)

9

In [125]:
np.prod(c)

362880

# Exercise 2 - Determine the standard deviation of c.



In [126]:
np.std(c)

2.581988897471611

# Exercise 3 - Determine the variance of c.



In [127]:
np.var(c)

6.666666666666667

# Exercise 4 - Print out the shape of the array c



In [128]:
np.shape(c)

(3, 3)

# Exercise 5 - Transpose c and print out transposed result.



In [129]:
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Exercise 6 - Get the dot product of the array c with c. 



In [131]:
np.vdot(c,c)

285

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261



In [140]:
np.vdot(c,np.transpose(c))

261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [145]:
np.prod(c * np.transpose(c))

131681894400

In [138]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

# Exercise 1 - Find the sine of all the numbers in d



In [141]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

# Exercise 2 - Find the cosine of all the numbers in d



In [143]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

# Exercise 3 - Find the tangent of all the numbers in d



In [146]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

# Exercise 4 - Find all the negative numbers in d



In [147]:
d[d < 0]

array([-90, -30, -45, -45])

# Exercise 5 - Find all the positive numbers in d



In [148]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

# Exercise 6 - Return an array of only the unique numbers in d.



In [151]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

# Exercise 7 - Determine how many unique numbers there are in d.



In [152]:
len(np.unique(d))

11

# Exercise 8 - Print out the shape of d.



In [153]:
np.shape(d)

(3, 6)

# Exercise 9 - Transpose and then print out the shape of d.



In [154]:
np.transpose(d)

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

# Exercise 10 - Reshape d into an array of 9 x 2

In [155]:
np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])